import datetime
import os

"""
This is a sample Python script that demonstrates how to
perform a Snagit COM image capture and save it to a file.

Support e-mail: support@techsmith.zendesk.com
This software is provided under the MIT License (http://opensource.org/licenses/MIT)
Copyright (c) 2023 TechSmith Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sub-license, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:
   The above copyright notice and this permission notice shall be included in all copies
   or substantial portions of the Software.
   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
   INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
   PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
   FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""
from snagitenums import *

import win32com.client


class SnagItCapture:
    def __init__(self):
        self.snagit = None
        self.current_time_stamp = None

    def setup_snagit_for_capture(self):
        self.snagit = win32com.client.gencache.EnsureDispatch("SNAGIT.ImageCapture.1")
        # print(win32com.__gen_path__) # Print path to win32 type library file generated by make.py
        self.snagit.Input = siiRegion
        self.snagit.Output = sioFile
        self.snagit.EnablePreviewWindow = False
        self.snagit.UseMagnifierWindow = False
        self.snagit.OutputImageFile.FileType = siftPNG
        self.snagit.IncludeCursor = False

    def set_screen_location(self):
        self.snagit.InputRegionOptions.SelectionMethod = srsmFixed
        self.snagit.InputRegionOptions.UseStartPosition = True
        self.snagit.InputRegionOptions.StartX = 538
        self.snagit.InputRegionOptions.StartY = 433
        self.snagit.InputRegionOptions.Height = 750
        self.snagit.InputRegionOptions.Width = 1017

    def set_file_options(self):
        self.snagit.OutputImageFile.FileNamingMethod = sofnmFixed
        # You must set the directory here, and not part of the filename, or you will get an exception
        self.snagit.OutputImageFile.Directory = os.getcwd()
        self.current_time_stamp = datetime.datetime.now().strftime("%Y-%m-%d_%H_%M_%S")
        self.snagit.OutputImageFile.Filename = self.current_time_stamp


def main():
    snagitcapture = SnagItCapture()
    snagitcapture.setup_snagit_for_capture()
    snagitcapture.set_screen_location()
    snagitcapture.set_file_options()
    snagitcapture.snagit.Capture()
    os.startfile(os.path.join(os.getcwd(), snagitcapture.current_time_stamp + ".png"))


if __name__ == "__main__":
    main()
